name: "🚀 CI Workflow"

on:
  push:
    branches:
      - master
  workflow_call: {}
  pull_request: {}

jobs:
  test:
    name: 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 16

      - name: 📥 Download deps
        run: yarn install

      - name: 🃏 Test
        run: yarn test
